#!/bash

false
set -e -u -o pipefail
shopt -s inherit_errexit &>/dev/null || true

bpan::init::main() {
  local init root
  init=${BASH_SOURCE[0]}
  root=$(cd "$(dirname "$init")" && pwd)

  export PATH=$root/lib:$root/bin:$PATH

  [[ -f $root/package.ini ]] ||
    bpan::init::die \
      "BPAN config file '$root/package.ini' not found"
  [[ $(command -v git) ]] ||
    bpan::init::die "BPAN requires 'git'. Please install it."

  local arg
  for arg; do
    case "$arg" in
      auto*) source "$root/lib/bpan-init-auto" "$arg" ;;
      vars*) source "$root/lib/bpan-init-vars" "$arg" ;;
      *) bpan::init::die "Unknown argument '$arg' for '$init'" ;;
    esac
  done
}

bpan::init::die() ( printf "%s\n" "$@" >&2; exit 1 )

bpan::init::main "$@"

unset -f bpan::init bpan::init::die
