#!/bash

bpan::init::vars() {
  local var
  while read -r var; do
    var=${var#*=}
    case "$var" in
      bpan_repo_root)
        bpan_repo_root=$(cd "$root" && git rev-parse --show-toplevel) ;;
        *) bpan::init::die "Unknown BPAN init var: '$var'" ;;
    esac
  done <<< \
    "$(git config -f "$root/package.ini" --list |
      grep "^bpan.init.${1//=/}.var="
    )"
}

bpan::init::vars "$@"

unset -f bpan::init::vars
